### PR TITLE
Fix error message LusterPortError: Can not unlink unix socket "undefined"

### LINKED ISSUE #31: Unhelpful error message: LusterPortError: Can not unlink unix socket "undefined"
Hi, guys.
You have an error in https://github.com/nodules/luster/blob/master/lib/port.js#L110
You use `this.value` inside callback which is always `undefined`.

### PR DESCRIPTION
**Pull request by narqo**
closes #31

Additionally: 

- add `LusterPortError.UNKNOWN_ERROR` for unspecified errors during unlink.

/cc @kaero

### CODE REVIEW

File: lib/errors.js [hunk 1]
```diff
@@ -82,6 +82,3 @@ errors.LusterPortError = LusterError.create('LusterPortError',
         CAN_NOT_UNLINK_UNIX_SOCKET :
             'Can not unlink unix socket "%socketPath%"'
     });
-
-module.exports = errors;
-
```
Comment (kaero) [inline lib/errors.js]: It's not specified by linters rules, but, i think, it's common style in all the nodules. What the reason to break it?

File: lib/port.js [hunk 2]
```diff
@@ -91,23 +91,25 @@ Port.prototype.unlink = function(err, cb) {
     }
 
     if (err) {
-        // unknown error
-        cb(err);
+        cb(LusterPortError
+            .createError(LusterPortError.CODES.UNKNOWN_ERROR, err));
```
Comment (kaero) [inline lib/port.js]: `UNKNOWN_ERROR` code is used if particular code is not specified, isn't it?

File: lib/errors.js (hunk 1 above)
Comment (narqo) [inline lib/errors.js]: Crap, I hopped you won't notice :D

File: lib/port.js (hunk 2 above)
Comment (narqo) [inline lib/port.js]: Yeah, but it's better than

~~~js
LusterPortError.createError(undefined, err);
~~~

Isn't it?

https://github.com/nodules/terror/blob/88c6541d5fedbc4bf93aa17a79bcc2387db16415/lib/terror.js#L164-L178

Comment (kaero) [inline lib/port.js]: ok

**Comment by kaero** [comment]
lgtm, merge@release ;)
